<?php 
ob_start();
if(isset($_SESSION['valid'])){
    if(isset($passed_validation)){
        echo addNotification($passed_validation);
    }
    echo addNotification();
    
} 
else{
    echo "<h2>Unauthorized access. Login is required.<br>Redirecting to login page.<br><br>";
    header('Refresh: 3; URL =https://f9202754.gblearn.com/comp1230/assignments/assignment2/notificationSystem_database/public/');
}
echo "<a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source: addNotification.phtml</a> | "; ?>