<?php 
ob_start();
if(isset($_SESSION['valid'])){
    echo updateEvent($statements_current_event, $fields, $statements_clients, $statements_notifications);
} 
else{
    echo "<h2>Unauthorized access. Login is required.<br>Redirecting to login page.<br><br>";
    header('Refresh: 3; URL =https://f9202754.gblearn.com/comp1230/assignments/assignment2/notificationSystem_database/public/');
}
echo "<a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source: updateEvent.phtml</a> | "; ?>